import re


# ============================================================
# MVI opcode lookup table
# ============================================================

MVI_OPCODES = {
    "A": 0x3E,
    "B": 0x06,
    "C": 0x0E,
    "D": 0x16,
    "E": 0x1E,
    "H": 0x26,
    "L": 0x2E
}


# ============================================================
# Tokenize one assembly instruction
# ============================================================

def tokenize(instruction):
    instruction = instruction.strip().upper()

    # Make comma a separate token
    instruction = instruction.replace(",", " , ")

    return instruction.split()


# ============================================================
# Assemble one MVI instruction
# ============================================================

def assemble_mvi(tokens):

    # Check number of tokens
    if len(tokens) != 4:
        print("Error: Invalid instruction format.")
        print("Expected: MVI <register>, <8-bit hexadecimal value>.")
        return None

    # Check mnemonic
    if tokens[0] != "MVI":
        print("Error: Invalid instruction.")
        print("Only MVI is currently supported.")
        return None

    # Check destination register
    if tokens[1] not in MVI_OPCODES:
        print("Error: Invalid register.")
        print("Valid registers: A, B, C, D, E, H, L.")
        return None

    # Check comma
    if tokens[2] != ",":
        print("Error: Missing or invalid comma.")
        return None

    # Check hexadecimal format
    if not re.fullmatch(r"[0-9A-F]{2}H", tokens[3]):
        print("Error: Invalid data.")
        print("Expected an 8-bit hexadecimal value in the form XXH.")
        return None

    # Remove the H
    hex_value = tokens[3][:-1]

    # Convert hexadecimal text to an integer
    data = int(hex_value, 16)

    # Find opcode for destination register
    opcode = MVI_OPCODES[tokens[1]]

    return [opcode, data]


# ============================================================
# Main assembler
# ============================================================

machine_code = []
error_found = False

print("8085 Assembler")
print("Currently supported instruction: MVI")
print("Enter a blank line when finished.\n")


while True:

    instruction = input(">>> ")

    # Blank line = finished entering program
    if instruction.strip() == "":
        break

    tokens = tokenize(instruction)

    # Assemble instruction
    result = assemble_mvi(tokens)

    # If instruction was invalid
    if result is None:
        error_found = True
        print()
        continue

    # Add generated bytes to the complete program
    machine_code.extend(result)

    # Show what this instruction generated
    print(
        f"Machine code: "
        f"{result[0]:02X} {result[1]:02X}\n"
    )


# ============================================================
# Write program to memory file
# ============================================================

if error_found:

    print("Assembly failed.")
    print("program.mem was not modified.")

else:

    output_path = r"D:\Git_Verilog\verilog-hdl-projects\8085_One_instruc_demo\Assembler_codes\Assembler_gen_mem_files\program.mem"

    with open(output_path, "w") as mem_file:

        for byte in machine_code:
            mem_file.write(f"{byte:02X}\n")

    print("Assembly successful.")
    print(f"Generated {len(machine_code)} byte(s).")
    print(f"Output written to: {output_path}")